/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/base/BaseCard.vue')['default']
    BaseEmpty: typeof import('./src/components/base/BaseEmpty.vue')['default']
    BaseInput: typeof import('./src/components/form/BaseInput.vue')['default']
    BaseNavbar: typeof import('./src/components/base/BaseNavbar.vue')['default']
    BasePage: typeof import('./src/components/base/BasePage.vue')['default']
    BaseTag: typeof import('./src/components/base/BaseTag.vue')['default']
    BottomTab: typeof import('./src/components/base/BottomTab.vue')['default']
    CategoryTabs: typeof import('./src/components/clothes/CategoryTabs.vue')['default']
    ClothesCard: typeof import('./src/components/clothes/ClothesCard.vue')['default']
    ClothesGrid: typeof import('./src/components/clothes/ClothesGrid.vue')['default']
    ClothesPreview: typeof import('./src/components/clothes/ClothesPreview.vue')['default']
    ClothesSelector: typeof import('./src/components/clothes/ClothesSelector.vue')['default']
    FormLogo: typeof import('./src/components/form/FormLogo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    OutfitActionBar: typeof import('./src/components/outfit/OutfitActionBar.vue')['default']
    OutfitCard: typeof import('./src/components/outfit/OutfitCard.vue')['default']
    OutfitGrid: typeof import('./src/components/outfit/OutfitGrid.vue')['default']
    OutfitInfo: typeof import('./src/components/outfit/OutfitInfo.vue')['default']
    OutfitSwiper: typeof import('./src/components/outfit/OutfitSwiper.vue')['default']
    OutfitTagList: typeof import('./src/components/outfit/OutfitTagList.vue')['default']
    PasswordInput: typeof import('./src/components/form/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/base/SearchBar.vue')['default']
    SectionTitle: typeof import('./src/components/base/SectionTitle.vue')['default']
    StatCard: typeof import('./src/components/base/StatCard.vue')['default']
  }
}
